### ISSUE TITLE
An attempt has been made to start a new process before the  current process has finished its bootstrapping phase

### ISSUE THREAD

**Issue by RichardScottOZ** [geofileops/geofileops#466]
This is on a Windows 10 machine - 10000 points and 250K polygons intersection test.  Looks like an OS type issue - wondering if you had any idea what might be going on here?

```python
python geofile_intersection_test_10000.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rscott\Geology\geofile_intersection_test_10000.py", line 9, in <module>
    gfo.intersection(input1_path=collars, input2_path=geology, output_path=combo)
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\site-packages\geofileops\geoops.py", line 2267, in intersection
    return _geoops_sql.intersection(
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\site-packages\geofileops\util\_geoops_sql.py", line 1447, in intersection
    return _two_layer_vector_operation(
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\site-packages\geofileops\util\_geoops_sql.py", line 2586, in _two_layer_vector_operation
    future = calculate_pool.submit(
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\concurrent\futures\process.py", line 737, in submit
    self._adjust_process_count()
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\concurrent\futures\process.py", line 697, in _adjust_process_count
    self._spawn_process()
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\concurrent\futures\process.py", line 714, in _spawn_process
    p.start()
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Error <A process in the process pool was terminated abruptly while the future was running or pending.> executing {'layer': 'gdfCOLLARS_SURFACE_NLP_OPTION2_4283', 'tmp_partial_output_path': WindowsPath('C:/Users/rscott/AppData/Local/Temp/geofileops/intersection_000002/gdfCOLLARS.gpkg'), 'sqlite_stmt': '\n        SELECT sub.geom\n             ,sub."l1_DATA_SOURC", sub."l1_DRILLHOLE_", sub."l1_LONGITUDE_", sub."l1_LATITUDE_G", sub."l1_DH_NAME", sub."l1_MAX_DRILLE", sub."l1_DIP", sub."l1_AZIMUTH", sub."l1_X", sub."l1_Y"\n             ,sub."l2_SURFACE_KE", sub."l2_DESC", sub."l2_LITH", sub."l2_AGE", sub."l2_LEFT", sub."l2_RIGHT", sub."l2_nlp", sub."l2_unique_uni", sub."l2_priority", sub."l2_USEROW", sub."l2_TEXT", sub."l2_vecgeol", sub."l2_dist_sed", sub."l2_dist_met", sub."l2_dist_int", sub."l2_dist_ext", sub."l2_dist_fel", sub."l2_dist_maf", sub."l2_dist_ign", sub."l2_dist_vol", sub."l2_baseclass3", sub."l2_felmaf"\n          FROM\n            ( SELECT ST_CollectionExtract(\n                       ST_Intersection(\n                            layer1.geom,\n                            layer2.geom),\n                            0) AS geom\n                    ,layer1."DATA_SOURC" "l1_DATA_SOURC", layer1."DRILLHOLE_" "l1_DRILLHOLE_", layer1."LONGITUDE_" "l1_LONGITUDE_", layer1."LATITUDE_G" "l1_LATITUDE_G", layer1."DH_NAME" "l1_DH_NAME", layer1."MAX_DRILLE" "l1_MAX_DRILLE", layer1."DIP" "l1_DIP", layer1."AZIMUTH" "l1_AZIMUTH", layer1."X" "l1_X", layer1."Y" "l1_Y"\n                    ,layer2."SURFACE_KE" "l2_SURFACE_KE", layer2."DESC" "l2_DESC", layer2."LITH" "l2_LITH", layer2."AGE" "l2_AGE", layer2."LEFT" "l2_LEFT", layer2."RIGHT" "l2_RIGHT", layer2."nlp" "l2_nlp", layer2."unique_uni" "l2_unique_uni", layer2."priority" "l2_priority", layer2."USEROW" "l2_USEROW", layer2."TEXT" "l2_TEXT", layer2."vecgeol" "l2_vecgeol", layer2."dist_sed" "l2_dist_sed", layer2."dist_met" "l2_dist_met", layer2."dist_int" "l2_dist_int", layer2."dist_ext" "l2_dist_ext", layer2."dist_fel" "l2_dist_fel", layer2."dist_maf" "l2_dist_maf", layer2."dist_ign" "l2_dist_ign", layer2."dist_vol" "l2_dist_vol", layer2."baseclass3" "l2_baseclass3", layer2."felmaf" "l2_felmaf"\n                FROM {input1_databasename}."test_10000" layer1\n                JOIN {input1_databasename}."rtree_test_10000_geom" layer1tree\n                  ON layer1.fid = layer1tree.id\n                JOIN {input2_databasename}."gdfSURFACE_NLP_OPTION2_4283" layer2\n                JOIN {input2_databasename}."rtree_gdfSURFACE_NLP_OPTION2_4283_geom" layer2tree\n                  ON layer2.fid = layer2tree.id\n               WHERE 1=1\n                 AND (layer1.rowid >= 1 AND layer1.rowid <= 208) \n                 AND layer1tree.minx <= layer2tree.maxx\n                 AND layer1tree.maxx >= layer2tree.minx\n                 AND layer1tree.miny <= layer2tree.maxy\n                 AND layer1tree.maxy >= layer2tree.miny\n                 AND ST_Intersects(\n                        layer1.geom,\n                        layer2.geom) = 1\n                 --AND ST_Touches(\n                 --       layer1.geom,\n                 --       layer2.geom) = 0\n               LIMIT -1 OFFSET 0\n            ) sub\n         WHERE sub.geom IS NOT NULL\n    '}
Traceback (most recent call last):
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\site-packages\geofileops\util\_geoops_sql.py", line 2616, in _two_layer_vector_operation
    result = future.result()
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\daskgeopandas\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by RichardScottOZ** [comment]
e.g. could bad geometry issues etc. cause this?

**Comment by theroggy** [comment]
When multiprocessing is used, you should always use the following construct in your scripts, otherwise you get the error above...

```
if __name__ == '__main__':
    gfo. ...
```

**Comment by theroggy** [comment]
PS: I've never checked, but I'd guess that the intersection of a point with a polygon is not an expensive operations CPU wise. So possibly the overhead of using multiprocessing is larger than the gain from it...
